services:
  postgres:
    image: postgres:16-alpine
    container_name: gobron-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobron
    volumes:
      - gobron_pgdata:/var/lib/postgresql/data

volumes:
  gobron_pgdata:
